services:
  jenkins:
    image: jenkins/jenkins:2.471-jdk21
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - ${HOST_JENKINS_HOME}:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

    links:
      - worker-1

  worker-1:
    image: jenkins/ssh-agent:latest-jdk21
    volumes:
      - ${HOST_JENKINS_WORKER_1}:/home/jenkins
    environment:
      - JENKINS_SLAVE_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJYE3dydfbauZv9Zts/dbB/TloqGbTQk4RnZveodqITDO2pzggznjlslfmukMJCkzbO0OtbGOTG9yfn7bV/NrEcZNr7C8N0QGWPFjIU77+vQoKfSxJRGKT97O9VEU8veMRdgbgff9aHUbrlzvY+KCGEQsTPn162Rq3Je1Au94TCdKnesPjQmSu77zr6gQA0YZCiz19yt7TrBxzmoYWt1Dfo/BxqtdJUQ+KGJsYPT1OtcJHW4JydjumBCYjw62ECjHRFVdYGqo42UZ2PombHOpdvdqr800sdkETQsN/2OlHppN3LdyIfqqyRewzjXgcTnPJHvPffNvAreSyS7MoQOacFlojl97jXUGfCJCMBLhi4Y9oaG5Za8VMZ0PpPaGRlqfkZeZeL6vMzz4LSjLh6UshlYPyhQzBsjv9r+FShpJnEHErhS7n2tdW3btOM8969QyYnhPMtB3i1qy/OT3paqguutu7syr09k8evIl/rYkqDz0NMYa2Xi1Ap6d7WwD4ZAM=

  sonarqube:
    image: sonarqube:9-community
    ports:
      - "9000:9000"
